name: test-pipeline
on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      registry_id:
        required: true
        type: string
      commandline:
        required: true
        type: string
    secrets:
      DEPLOY_PAT:
        required: true
      DEPLOY_SSH_KEY:
        required: true
      FLEET_PAT:
        required: true
jobs:
  Image:
    runs-on: self-hosted
    container: ${{ inputs.registry_id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/esma:stable
    steps:
      - name: Parse environment
        id: set-env
        run: |
          cl="${{ inputs.commandline }}"
          env=${cl#"/deploy "}
          echo "::set-output name=environment::$env"
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha 
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.sha.outputs.result }}
          submodules: true
          token: ${{ secrets.DEPLOY_PAT }}
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - uses: actions/checkout@v2
        with:
          repository: lifesum/platform-build-pipeline-github-action
          token: ${{ secrets.FLEET_PAT }}
          path: .github/actions
      - name: Build pipeline
        uses: ./.github/actions
        with:
          fleet_pat: ${{ secrets.FLEET_PAT }}
          fleet_branch: ${{ steps.set-env.outputs.environment }}
